### ISSUE TITLE
Dates not consistent

### ISSUE THREAD

**Issue by TorMec** [tillbiskup/dokuwiki-caption#1]
Hi,
in the `​plugin.info.txt` it's written: 
`​date ​  ​2011-04-13`
	
while, in https://www.dokuwiki.org/plugin:caption it's written: 
​`lastupdate : 2013-08-24`

As described in https://www.dokuwiki.org/devel:plugin_info (see the note at the bottom of the page), this means that Extension Manager will always says that there is a new upgrade. Please, correct one of the dates.

Thanks

**Comment by tillbiskup** [comment]
Thanks a lot for spotting this. It should be fixed by now.
