### ISSUE TITLE
Start with other number than 1

### ISSUE THREAD

**Issue by arjay54** [tillbiskup/dokuwiki-caption#12]
I am using the caption plugin for a documentation on several pages. Is it possible to start numbering with a defined number instead of 1?

**Comment by tillbiskup** [comment]
Hi there. Just in case you are still interested, I've managed to come up with a solution. An example would  look like this:

```{{setcounter figure=5}}```

This would set the figure counter to 5. You can set the counter for all types (figure, table, codeblock, fileblock) anywhere on your wiki page.
