### ISSUE TITLE
Warning label not defined

### ISSUE THREAD

**Issue by tormec** [tillbiskup/dokuwiki-caption#18]
If there is no label in the opening tag, like:
```
<figure>  // no label in the opening tag
{{:image.png?400|}}
<caption>caption</caption>
</figure>
```
the following warning is raised (with PHP >= 8):

`Warning: Undefined array key 1 in /dokuwiki/lib/plugins/caption/syntax/caption.php on line 109`

A solution could be to replace this line:
https://github.com/tillbiskup/dokuwiki-caption/blob/254677ce1544a9efdf6180c14f5971d3bc0b00d9/syntax/caption.php#L109
with:
```
$match = explode(' ',$match)[0];
$label = count(explode(' ',$match)) > 1 ? explode(' ',$match)[1] : null;
```

Edit 15/04/23:
I've noticed that it's the same issue that PR #17 try to solve.

**Comment by tillbiskup** [comment]
Thanks a lot for the issue and for the suggestion. I finally managed to get it fixed.

Your suggestion would work with both, older and newer versions of DokuWiki (as the function "sexplode" was only introduced in "Jack Jackrum"), and what I've now done is checking for the existence of this DokuWiki function and handle the situation accordingly.

**Comment by tormec** [comment]
Mere curiosity, but I didn't understand the necessity to keep both options, since they return the same result but one is independent of the DokuWiki version.

**Comment by tillbiskup** [comment]
Thanks for catching up. Just me coding first and thinking afterwards (and fighting with PHP after a long time, thus getting distracted). Fixed it, i.e., removed unnecessary option and if clause.
