### ISSUE TITLE
Figure caption doesn't follow image alignment

### ISSUE THREAD

**Issue by eduardomozart** [tillbiskup/dokuwiki-caption#22]
It would be great if the Caption plugin position it's label respecting the image alignment.

Here's the image without the Caption plugin:

<img width="696" alt="image" src="https://github.com/tillbiskup/dokuwiki-caption/assets/2974895/b62ee947-1aea-417b-a97d-91250ba83845">

Here's the image with Caption plugin:

![image](https://github.com/tillbiskup/dokuwiki-caption/assets/2974895/83dd222f-2b6a-4909-af60-d613836c9da1)

**Comment by tillbiskup** [comment]
Apologies for the delay... Very valid feature request.
Currently, I have no clue how to directly use the information of the image alignment from the image dokuwiki syntax. But would an additional alignment option in the figure tag be an option as well? I could think of something like this:

```
<figure mylabel align=right>
...
<caption>Lorem ipsum...</caption>
</figure>
```

Any suggestions welcome.
