### ISSUE TITLE
An incorrect date in plugin.info.txt

### ISSUE THREAD

**Issue by alexgearbox** [tillbiskup/dokuwiki-caption#7]
https://github.com/tillbiskup/dokuwiki-caption/blob/c6594d2b4dff81a286cc24318943f8a719e6ce6e/plugin.info.txt#L4

Hi!

The date in `plugin.info.txt` should be like a date of a last commit (2019-05-21).

**Comment by tillbiskup** [comment]
Thanks a lot. Fixed (and updated corresponding dokuwiki plugin page).

**Comment by alexgearbox** [comment]
Thank you to.
