### ISSUE TITLE
add caption for code and file syntax

### ISSUE THREAD

**Issue by chaotic-bruno** [tillbiskup/dokuwiki-caption#9]
Hey,

it would be nice if this plugin could also do captions for the <code [lang]></code> and <file [lang] [filename]></file> syntax.

Doesn't seem too hard. I don't have enough time to make a PR right now.

Things to be added:
- new "codeblock" and new "fileblock"? (reference numbers should be counted independently)
-> discussion needed (counter + naming)

**Comment by tillbiskup** [comment]
Hi there,

excellent idea. Unfortunately, I have currently not enough time to implement it, but I'll definitely look into it asap.

For starters, "codeblock" and "fileblock" seem to be good names. Could change during development if necessary.

**Comment by kabbala** [comment]
It is interesting suggestion.

but I think this plugin works in latex way, so codes like below have clearer structure.

```
<wrap_or_something equation>
    <caption>...</caption>
    <something>
</wrap>
```
and this style code can minimize regex handler.

**Comment by tillbiskup** [comment]
The newest version of the plugin supports both "fileblock" and "codeblock", like that:

```
<codeblock label>
    <caption>...</caption>
    <code>
    ...
    </code>
</codeblock>
```

```
<fileblock label>
    <caption>...</caption>
    <file "" filename.ext>
    ...
    </file>
</fileblock>
```
